/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CreatorsIndexRouteImport } from './routes/creators.index'
import { Route as CreatorsRegisterRouteImport } from './routes/creators.register'
import { Route as CreatorsSlugRouteImport } from './routes/creators.$slug'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorsIndexRoute = CreatorsIndexRouteImport.update({
  id: '/creators/',
  path: '/creators/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorsRegisterRoute = CreatorsRegisterRouteImport.update({
  id: '/creators/register',
  path: '/creators/register',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorsSlugRoute = CreatorsSlugRouteImport.update({
  id: '/creators/$slug',
  path: '/creators/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/creators/$slug': typeof CreatorsSlugRoute
  '/creators/register': typeof CreatorsRegisterRoute
  '/creators/': typeof CreatorsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/creators/$slug': typeof CreatorsSlugRoute
  '/creators/register': typeof CreatorsRegisterRoute
  '/creators': typeof CreatorsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/creators/$slug': typeof CreatorsSlugRoute
  '/creators/register': typeof CreatorsRegisterRoute
  '/creators/': typeof CreatorsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/register'
    | '/creators/$slug'
    | '/creators/register'
    | '/creators/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/register' | '/creators/$slug' | '/creators/register' | '/creators'
  id:
    | '__root__'
    | '/'
    | '/register'
    | '/creators/$slug'
    | '/creators/register'
    | '/creators/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RegisterRoute: typeof RegisterRoute
  CreatorsSlugRoute: typeof CreatorsSlugRoute
  CreatorsRegisterRoute: typeof CreatorsRegisterRoute
  CreatorsIndexRoute: typeof CreatorsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creators/': {
      id: '/creators/'
      path: '/creators'
      fullPath: '/creators/'
      preLoaderRoute: typeof CreatorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creators/register': {
      id: '/creators/register'
      path: '/creators/register'
      fullPath: '/creators/register'
      preLoaderRoute: typeof CreatorsRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creators/$slug': {
      id: '/creators/$slug'
      path: '/creators/$slug'
      fullPath: '/creators/$slug'
      preLoaderRoute: typeof CreatorsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RegisterRoute: RegisterRoute,
  CreatorsSlugRoute: CreatorsSlugRoute,
  CreatorsRegisterRoute: CreatorsRegisterRoute,
  CreatorsIndexRoute: CreatorsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
